/* Type & Chill — frases de exemplo.
 *
 * "Frase de exemplo é obrigatória se a campanha e a revisão vão existir — é o
 * contexto que faz a palavra grudar." (documento de design)
 *
 * Uma palavra sozinha com a tradução ao lado ensina a reconhecer; uma palavra
 * dentro de uma frase ensina a usar. É a frase que vai para o cartão do fim da
 * captura, para o caderno, para o CSV e para o cartão do Anki.
 *
 * Regras das frases, e os testes conferem todas:
 *   · precisam conter a própria palavra (flexão regular vale: walk → walked);
 *   · curtas — de seis a doze palavras, para ler num piscar durante a partida;
 *   · nível parecido com o da palavra: uma frase C1 não pode ensinar um A2;
 *   · nada de vírgulas obrigatórias no meio do sentido, nem nomes próprios
 *     difíceis, que só distraem de quem é a estrela da frase.
 *
 * Para adicionar palavras novas ao banco, adicione a frase aqui também: o
 * npm test mede a cobertura e reclama quando ela cai.
 */
(function (root) {
  "use strict";

  var WORD_EXAMPLES = {

  /* Dia a dia */
  "tidy": "Her desk is always tidy before she leaves.",
  "borrow": "Can I borrow your umbrella until tomorrow?",
  "spare": "I keep a spare key under the plant.",
  "handy": "A small flashlight is handy during a blackout.",
  "routine": "My morning routine starts with coffee and the news.",
  "schedule": "The schedule says the meeting starts at nine.",
  "chore": "Washing the dishes is my least favorite chore.",
  "messy": "His room was messy after a long week.",
  "gather": "Friends gather at the park every Sunday.",
  "improve": "Reading every night will improve your English.",
  "plenty": "There is plenty of rice left for dinner.",
  "habit": "Checking my phone in bed is a bad habit.",
  "alarm": "My alarm rings at six in the morning.",
  "weekend": "We stayed home the whole weekend and rested.",
  "errand": "I have one errand left: mailing this letter.",
  "mend": "She sat down to mend the torn sleeve.",
  "frequent": "He is a frequent visitor at that little cafe.",
  "convenient": "The store opens late, which is very convenient.",
  "swift": "The waiter gave us a swift and friendly reply.",
  "fetch": "Could you fetch a chair from the kitchen?",
  "abundant": "Rain is abundant here in the summer months.",
  "occasional": "She drinks an occasional cup of tea at night.",
  "punctual": "Please be punctual; the train leaves at seven.",
  "spotless": "The kitchen counter was spotless after cleaning.",
  "laundry": "I still have two loads of laundry to do.",
  "chatter": "The children chatter happily on the school bus.",
  "linger": "We lingered at the table long after dinner.",
  "nudge": "He nudged me when the film finally started.",
  "hassle": "Parking downtown is always a hassle.",
  "tuck": "He tucked the map into his back pocket.",
  "knack": "She has a knack for fixing old radios.",
  "mundane": "Even mundane tasks feel lighter with music.",
  "makeshift": "We built a makeshift table from two boxes.",

  /* Casa & objetos */
  "shelf": "The books sit on the top shelf.",
  "drawer": "My socks are in the second drawer.",
  "broom": "He swept the porch with an old broom.",
  "rent": "They rent a small flat near the station.",
  "curtain": "Close the curtain; the sun is too bright.",
  "gadget": "This gadget peels an apple in five seconds.",
  "sturdy": "The table is sturdy enough to stand on.",
  "kettle": "Put the kettle on and make some tea.",
  "spacious": "Their new apartment is bright and spacious.",
  "cozy": "The living room feels cozy in winter.",
  "fragile": "Handle the box carefully; the glass is fragile.",
  "faucet": "The kitchen faucet is dripping again.",
  "balcony": "We drink coffee on the balcony every morning.",
  "landlord": "Our landlord fixed the heater last week.",
  "tenant": "The new tenant moved in on Monday.",
  "ceiling": "A small lamp hangs from the ceiling.",
  "hallway": "Their photos line the narrow hallway.",
  "fence": "A wooden fence surrounds the garden.",
  "basement": "We keep old boxes in the basement.",
  "cottage": "They spent August in a seaside cottage.",
  "cupboard": "The plates are in the cupboard above the sink.",
  "cushion": "She put a cushion behind her back.",
  "mattress": "This mattress is too soft for my back.",
  "clutter": "Clear the clutter off the dining table.",
  "household": "Our household shares the cleaning every Saturday.",
  "dwelling": "The old dwelling has stood here for a century.",
  "renovate": "They plan to renovate the kitchen this spring.",
  "cluttered": "His desk is cluttered with papers and cups.",
  "cramped": "Four people in that little car felt cramped.",
  "vacant": "The shop next door has been vacant for months.",
  "doorstep": "The package was left on the doorstep.",
  "dilapidated": "Nobody has lived in that dilapidated house for years.",

  /* Comida & bebida */
  "grocery": "The grocery bag tore on the way home.",
  "bake": "She bakes bread every Sunday morning.",
  "boil": "Boil the water before adding the pasta.",
  "slice": "He cut a thick slice of bread.",
  "tasty": "That soup was simple but very tasty.",
  "sour": "The lemon juice was too sour for me.",
  "ripe": "These bananas will be ripe by Friday.",
  "snack": "I need a small snack before the gym.",
  "recipe": "This recipe comes from my grandmother.",
  "chop": "Chop the onion into small pieces.",
  "stir": "Stir the sauce so it does not burn.",
  "flavor": "The soup has a deep, smoky flavor.",
  "roast": "We roast potatoes with rosemary and salt.",
  "simmer": "Let the stew simmer for twenty minutes.",
  "season": "Season the fish with salt and pepper.",
  "crisp": "The apple was cold and wonderfully crisp.",
  "chewy": "These cookies are soft and chewy inside.",
  "bland": "Without salt the rice tasted bland.",
  "nourish": "Warm soup nourishes you on a cold day.",
  "portion": "The portion was too large to finish.",
  "leftovers": "We ate the leftovers for lunch today.",
  "brew": "He brews coffee before anyone else wakes up.",
  "sip": "She took a slow sip of hot tea.",
  "ingredient": "Butter is the main ingredient in this cake.",
  "dough": "Let the dough rest for one hour.",
  "seasoning": "A little seasoning made all the difference.",
  "savory": "I prefer savory food to sweet desserts.",
  "hearty": "We had a hearty breakfast before hiking.",
  "fragrant": "The kitchen was fragrant with fresh basil.",
  "zest": "Add lemon zest to the cake batter.",
  "marinate": "Marinate the chicken overnight for more flavor.",
  "garnish": "He garnished the plate with fresh parsley.",
  "knead": "Knead the dough until it feels smooth.",
  "whisk": "Whisk the eggs until they turn pale.",
  "sizzle": "The onions sizzle as they hit the pan.",
  "craving": "I had a sudden craving for chocolate.",
  "nutritious": "Beans are cheap and very nutritious.",
  "stale": "The bread went stale after three days.",
  "sumptuous": "They served a sumptuous dinner for their guests.",
  "palate": "Years of cooking gave him a fine palate.",
  "decadent": "The chocolate cake was rich and decadent.",
  "succulent": "The mango was juicy and succulent.",
  "culinary": "She studied culinary arts in Lyon.",
  "delectable": "The bakery smells absolutely delectable.",

  /* Roupa & estilo */
  "sleeve": "He rolled up his left sleeve.",
  "pocket": "My keys are in my coat pocket.",
  "button": "A button fell off my shirt.",
  "zipper": "The zipper on my bag is stuck.",
  "scarf": "She wore a red scarf against the wind.",
  "glove": "I lost one glove on the bus.",
  "boot": "His boots were covered in mud.",
  "jacket": "Take a jacket; the night gets cold.",
  "cotton": "This shirt is pure cotton and very light.",
  "sandal": "She wore sandals all summer long.",
  "fabric": "The fabric feels soft against the skin.",
  "leather": "He carries an old leather bag.",
  "collar": "Fix your collar before the photo.",
  "apron": "The cook tied a white apron around his waist.",
  "outfit": "Her outfit was perfect for the party.",
  "stitch": "She stitched the button back on.",
  "baggy": "He wears baggy jeans and old sneakers.",
  "elegant": "She looked elegant in a simple black dress.",
  "trendy": "That cafe is trendy with the students.",
  "hem": "The hem of her dress was coming loose.",
  "seam": "The seam split when he bent down.",
  "wardrobe": "Half my wardrobe no longer fits me.",
  "garment": "Wash this garment in cold water.",
  "snug": "The new boots feel snug but comfortable.",
  "shabby": "He wore a shabby coat with torn pockets.",
  "attire": "The invitation asked for formal attire.",
  "impeccable": "His manners are impeccable at the table.",
  "flamboyant": "The singer wore a flamboyant gold suit.",
  "understated": "Her style is understated and expensive.",
  "dapper": "He looked dapper in his grey suit.",

  /* Dinheiro & compras */
  "afford": "We cannot afford a new car this year.",
  "salary": "Her salary covers the rent and a little more.",
  "budget": "Our monthly budget leaves room for books.",
  "discount": "Students get a ten percent discount here.",
  "receipt": "Keep the receipt in case it breaks.",
  "currency": "The local currency is stronger than last year.",
  "invoice": "Please send the invoice by the end of the week.",
  "refund": "The store gave me a full refund.",
  "bargain": "That coat was a real bargain at half price.",
  "expense": "Rent is our largest monthly expense.",
  "income": "Most of his income goes to his family.",
  "savings": "She used her savings to buy a laptop.",
  "loan": "He took a small loan to fix the roof.",
  "debt": "They paid off the debt in two years.",
  "wage": "The daily wage barely covers the bus fare.",
  "profit": "The bakery made a small profit last month.",
  "purchase": "He purchased the tickets online yesterday.",
  "affordable": "This neighborhood is still affordable for students.",
  "pricey": "Coffee at the airport is always pricey.",
  "thrifty": "My thrifty aunt never wastes a coin.",
  "revenue": "The app doubled its revenue this year.",
  "invest": "They invest a little money every month.",
  "installment": "The first installment is due in March.",
  "mortgage": "We still have twelve years of mortgage left.",
  "insurance": "Travel insurance saved us on that trip.",
  "inflation": "Inflation made the weekly shopping more expensive.",
  "frugal": "He lives a frugal life and saves half his pay.",
  "lucrative": "Teaching online turned out to be lucrative.",
  "dividend": "The company pays a dividend every quarter.",
  "austerity": "Years of austerity closed many small libraries.",
  "windfall": "The unexpected windfall paid for the whole trip.",

  /* Gente & jeitos */
  "neighbor": "My neighbor waters my plants when I travel.",
  "gentle": "She has a gentle voice and a calm smile.",
  "polite": "He was polite even when he disagreed.",
  "bold": "It was a bold decision to leave the job.",
  "honest": "Give me an honest answer, please.",
  "shy": "The boy was too shy to ask a question.",
  "stranger": "A stranger helped me carry the boxes.",
  "relative": "Every relative came to the wedding.",
  "greet": "She greets everyone by name at the office.",
  "reliable": "He is the most reliable person on the team.",
  "genuine": "Her surprise at the party was genuine.",
  "awkward": "There was an awkward silence after the joke.",
  "stubborn": "My grandfather is stubborn about his routine.",
  "generous": "The tip was generous for such a small meal.",
  "grateful": "I am grateful for all your help today.",
  "patient": "Be patient; the line moves slowly.",
  "whisper": "She whispered the answer so nobody would hear.",
  "diligent": "A diligent student reviews a little every day.",
  "ambitious": "He is ambitious and wants to run the company.",
  "sincere": "Her apology sounded completely sincere.",
  "humble": "He stayed humble after winning the prize.",
  "timid": "The timid cat hid under the sofa.",
  "loyal": "They have been loyal friends for twenty years.",
  "selfish": "It felt selfish to take the last piece.",
  "outgoing": "My outgoing sister knows the whole street.",
  "reserved": "He is reserved with people he has just met.",
  "companion": "The dog was her companion on every walk.",
  "rival": "Their old rival won the match this time.",
  "sibling": "I have one sibling, a younger brother.",
  "witty": "His witty answer made the whole room laugh.",
  "blunt": "She was blunt about what needed to change.",
  "modest": "He is modest about his own success.",
  "acquaintance": "He is an acquaintance from my old gym.",
  "gossip": "Office gossip travels faster than email.",
  "befriend": "She befriended the new student on day one.",
  "quarrel": "They quarreled over something very small.",
  "meticulous": "His notes are meticulous and easy to follow.",
  "charismatic": "The charismatic teacher filled every class.",
  "candid": "Thank you for such a candid answer.",
  "aloof": "He seemed aloof, but he was only tired.",
  "gregarious": "Our gregarious host talked to every guest.",
  "amiable": "The amiable driver chatted the whole way.",

  /* Emoções & mente */
  "eager": "The children were eager to open the boxes.",
  "proud": "I am proud of how hard you worked.",
  "cheerful": "She stayed cheerful through the long delay.",
  "mood": "Rain always puts him in a quiet mood.",
  "curious": "The cat was curious about the new box.",
  "imagine": "Imagine a house right beside the sea.",
  "confident": "She felt confident before the interview.",
  "anxious": "He was anxious about the test results.",
  "weary": "We arrived weary after nine hours of driving.",
  "content": "He was content with a small, quiet life.",
  "hesitate": "Do not hesitate to ask for help.",
  "gloomy": "The news left everyone feeling gloomy.",
  "tender": "She gave the baby a tender look.",
  "recall": "I cannot recall his last name.",
  "comfort": "A warm drink comforts you on a bad day.",
  "admire": "I admire the patience of good teachers.",
  "forgive": "It took years to forgive that mistake.",
  "relieve": "A short walk relieves the tension.",
  "restless": "The restless dog paced by the door.",
  "fond": "She is fond of old black and white films.",
  "cherish": "I cherish the letters my father wrote.",
  "ponder": "He sat by the window and pondered the offer.",
  "astonish": "Her progress astonished the whole class.",
  "soothe": "Soft music soothes him before sleep.",
  "yearn": "They yearn for a quieter life in the country.",
  "dread": "I dread the first cold morning of winter.",
  "resent": "He resented having to work every weekend.",
  "empathy": "Good nurses work with real empathy.",
  "vivid": "She has vivid memories of that summer.",
  "overwhelm": "The kindness of strangers overwhelmed him.",
  "grief": "Grief comes and goes in slow waves.",
  "nostalgia": "The old song filled her with nostalgia.",
  "compassion": "He treats every patient with compassion.",
  "reassure": "The doctor reassured us about the results.",
  "apprehensive": "I felt apprehensive before my first flight.",
  "exhilarating": "The ride down the hill was exhilarating.",
  "wistful": "She gave the empty house a wistful look.",
  "serenity": "There is a strange serenity in early mornings.",
  "poignant": "The last scene of the film was poignant.",
  "elated": "They were elated when the results arrived.",
  "indifferent": "He seemed indifferent to the whole argument.",
  "introspective": "Long walks make me introspective.",
  "solace": "She found solace in painting after the loss.",
  "ambivalent": "I am ambivalent about moving to another city.",

  /* Corpo & saúde */
  "breathe": "Breathe slowly and let your shoulders drop.",
  "stretch": "Stretch your legs after sitting for hours.",
  "rest": "You need to rest for a few days.",
  "ache": "A dull ache spread across his back.",
  "healthy": "She stays healthy by walking every morning.",
  "wound": "The wound healed faster than expected.",
  "dizzy": "I felt dizzy after standing up too fast.",
  "sneeze": "He sneezed three times in a row.",
  "heal": "Small cuts heal in about a week.",
  "swollen": "Her ankle was swollen after the fall.",
  "sore": "My legs are sore from yesterday.",
  "recover": "It took a month to recover fully.",
  "posture": "Good posture makes long hours easier.",
  "exhausted": "We were exhausted after the whole journey.",
  "nutrition": "Good nutrition matters more than any pill.",
  "symptom": "A cough is the most common symptom.",
  "remedy": "Honey and lemon is her favorite remedy.",
  "strain": "He felt a strain in his shoulder.",
  "pulse": "The nurse checked my pulse and smiled.",
  "appetite": "The long walk gave me an appetite.",
  "bruise": "A small bruise appeared on his arm.",
  "hydrate": "Hydrate well before a long run.",
  "fatigue": "Fatigue set in around the fourth hour.",
  "soothing": "The warm bath was deeply soothing.",
  "nourishing": "A nourishing soup is enough for dinner.",
  "endurance": "Running builds endurance week by week.",
  "flexible": "Daily stretching keeps you flexible.",
  "immune": "Sleep keeps the immune system strong.",
  "insomnia": "Coffee at night gives me insomnia.",
  "mindful": "Try to be mindful of your breathing.",
  "restorative": "A short nap can be restorative.",
  "chronic": "He lives with chronic back pain.",
  "relapse": "She had a brief relapse after the flu.",
  "invigorating": "The cold sea air was invigorating.",
  "resilience": "His resilience surprised the whole family.",
  "sedentary": "A sedentary job needs a daily walk.",
  "ailment": "It was a minor ailment, nothing serious.",
  "convalesce": "He went to the coast to convalesce.",
  "vitality": "The garden gave her a new vitality.",

  /* Esportes & jogos */
  "team": "Our team trains twice a week.",
  "match": "The match was delayed by heavy rain.",
  "coach": "The coach changed the plan at halftime.",
  "score": "He scored twice in the second half.",
  "kick": "She kicked the ball over the fence.",
  "catch": "He ran back to catch the high ball.",
  "swim": "They swim in the lake every summer.",
  "climb": "We climbed the hill before sunrise.",
  "jog": "I jog around the park after work.",
  "referee": "The referee stopped the game for a minute.",
  "opponent": "His opponent was faster but less accurate.",
  "tournament": "The school tournament lasts three days.",
  "trophy": "The trophy sits on the club shelf.",
  "workout": "A short workout is better than none.",
  "dribble": "He dribbled past two defenders.",
  "sprint": "She sprinted the last hundred meters.",
  "dive": "He dived into the cold pool.",
  "stamina": "Long swims build real stamina.",
  "underdog": "Everyone cheered for the underdog.",
  "rally": "That rally lasted almost a minute.",
  "forfeit": "They had to forfeit the match after the injury.",
  "agile": "The goalkeeper is quick and agile.",
  "fierce": "The final set was a fierce battle.",
  "momentum": "One goal gave them all the momentum.",
  "relentless": "Their defense was relentless all night.",
  "formidable": "The visiting team is a formidable rival.",
  "prowess": "His prowess on clay courts is famous.",
  "decisive": "Her last shot was decisive.",

  /* Natureza & paisagem */
  "shore": "We walked along the shore at sunset.",
  "stream": "A small stream runs behind the house.",
  "pebble": "He threw a pebble into the water.",
  "valley": "Fog fills the valley every morning.",
  "shallow": "The water is shallow near the rocks.",
  "cave": "The cave stayed cool even in August.",
  "summit": "We reached the summit before noon.",
  "horizon": "The sun dropped below the horizon.",
  "blossom": "The cherry trees blossom in April.",
  "meadow": "Bees move slowly across the meadow.",
  "ripple": "A single ripple crossed the still lake.",
  "fern": "A green fern grows beside the path.",
  "moss": "Soft moss covers the old stone wall.",
  "tide": "The tide takes the boats out at dawn.",
  "vast": "The desert felt vast and completely silent.",
  "wander": "We wandered through the woods for hours.",
  "drift": "Leaves drift slowly down the river.",
  "steep": "The path is steep for the last kilometer.",
  "cliff": "Birds nest along the high cliff.",
  "sprout": "The seeds sprout after a week of rain.",
  "lush": "The valley is lush after the wet season.",
  "canopy": "Light barely reaches through the canopy.",
  "glacier": "The glacier has retreated since the photo.",
  "grove": "They rested in a small olive grove.",
  "serene": "The lake looked serene at first light.",
  "barren": "Nothing grows on that barren slope.",
  "fertile": "The fertile soil gives two harvests a year.",
  "radiant": "The morning sky was radiant with color.",
  "blaze": "The campfire blazed until midnight.",
  "hollow": "A rabbit hid in a hollow near the fence.",
  "marsh": "Frogs sing in the marsh all night.",
  "thrive": "These plants thrive in shade and damp air.",
  "wither": "The flowers withered in the August heat.",
  "rustle": "The wind made the tall grass rustle.",
  "cascade": "A small cascade falls behind the rocks.",
  "ember": "One ember still glowed in the ashes.",
  "meander": "The river meanders across the flat plain.",
  "glisten": "The wet leaves glisten after the rain.",
  "tranquil": "The bay is tranquil in the early morning.",
  "pristine": "The beach was pristine and almost empty.",
  "verdant": "Verdant hills surround the small village.",
  "dappled": "The path was dappled with afternoon light.",

  /* Bichos */
  "fur": "The cat has thick winter fur.",
  "feather": "A grey feather fell onto the balcony.",
  "paw": "The dog lifted a muddy paw.",
  "tail": "The horse swept flies away with its tail.",
  "wing": "The bird stretched one wing in the sun.",
  "nest": "Two birds built a nest above the door.",
  "bark": "Our dog barks at every delivery.",
  "migrate": "These birds migrate south in October.",
  "flock": "A flock of geese crossed the field.",
  "claw": "The cat sharpened its claws on the rug.",
  "beak": "The bird cleaned its beak on a branch.",
  "herd": "A herd of cows blocked the narrow road.",
  "hatch": "The eggs hatched early this spring.",
  "purr": "The cat purrs whenever she sits down.",
  "creature": "A small creature moved in the tall grass.",
  "hibernate": "Bears hibernate through the coldest months.",
  "graze": "Sheep graze on the hill above the village.",
  "swarm": "A swarm of bees passed over the garden.",
  "prey": "The owl carried its prey to the barn.",
  "burrow": "A rabbit disappeared into its burrow.",
  "howl": "Wolves howl on clear winter nights.",
  "livestock": "The farm keeps livestock and grows corn.",
  "predator": "The fox is the main predator here.",
  "habitat": "This forest is the habitat of many birds.",
  "species": "The lake holds three species of fish.",
  "venom": "The snake uses venom to catch its food.",
  "tame": "The parrot is tame and sits on my hand.",
  "stray": "A stray followed us all the way home.",
  "feral": "Feral cats live behind the old market.",
  "nocturnal": "Owls are nocturnal and hunt after dark.",
  "camouflage": "The moth uses camouflage to hide on bark.",

  /* Tempo & céu */
  "breeze": "A cool breeze came off the water.",
  "dawn": "We left the house before dawn.",
  "dusk": "The birds go quiet at dusk.",
  "thunder": "Thunder woke the whole house at night.",
  "sunny": "It was sunny all weekend long.",
  "cloudy": "The morning was cloudy but dry.",
  "windy": "It is too windy for the umbrella.",
  "storm": "The storm knocked out the power.",
  "shower": "A quick shower cooled the afternoon.",
  "dew": "Dew covered the grass at sunrise.",
  "frost": "Frost turned the windows white.",
  "misty": "The lake was misty at seven in the morning.",
  "drizzle": "A light drizzle fell all afternoon.",
  "chilly": "The evenings get chilly in October.",
  "humid": "August here is hot and humid.",
  "damp": "The towels are still damp from yesterday.",
  "forecast": "The forecast promises rain on Sunday.",
  "hail": "Hail bounced off the parked cars.",
  "lightning": "Lightning lit the whole valley for a second.",
  "flood": "The flood reached the bottom of the street.",
  "twilight": "We walked home in the blue twilight.",
  "haze": "A soft haze hid the far mountains.",
  "drought": "The drought lasted the entire summer.",
  "blizzard": "The blizzard closed every road north.",
  "overcast": "The sky stayed overcast for a week.",
  "scorching": "It was scorching at midday.",
  "gust": "A sudden gust took his hat away.",
  "thaw": "The snow began to thaw by noon.",
  "monsoon": "The monsoon brings rain every afternoon.",
  "gale": "A gale kept the boats in the harbor.",
  "sultry": "The sultry night made sleeping hard.",
  "torrential": "Torrential rain flooded the lower streets.",
  "balmy": "We ate outside on a balmy evening.",

  /* Cidade & ruas */
  "crowded": "The train was crowded at eight in the morning.",
  "street": "Our street is quiet after nine.",
  "bridge": "The old bridge crosses the river here.",
  "market": "The market opens early on Saturdays.",
  "library": "I study at the library near the park.",
  "rooftop": "We watched the fireworks from the rooftop.",
  "corner": "There is a bakery on the corner.",
  "noisy": "The bar downstairs is noisy on Fridays.",
  "downtown": "She works downtown and walks home.",
  "subway": "The subway runs until midnight.",
  "crosswalk": "Wait at the crosswalk for the green light.",
  "alley": "A narrow alley leads to the courtyard.",
  "sidewalk": "The sidewalk was wet and slippery.",
  "district": "This district is full of small bookshops.",
  "skyline": "The skyline changes every single year.",
  "suburb": "They moved to a quiet suburb last spring.",
  "traffic": "Traffic is heavy before every holiday.",
  "curb": "He parked too close to the curb.",
  "graffiti": "Bright graffiti covers the old wall.",
  "commuter": "Every commuter knows that delay by heart.",
  "pedestrian": "A pedestrian waved the car through.",
  "courtyard": "Children play in the shaded courtyard.",
  "outskirts": "The factory sits on the outskirts of town.",
  "plaza": "Musicians play in the plaza on Sundays.",
  "thoroughfare": "This avenue is the main thoroughfare.",
  "labyrinthine": "The old town is labyrinthine and lovely.",
  "sprawling": "The sprawling city took hours to cross.",
  "hub": "The station is the transport hub of the region.",

  /* Viagem */
  "journey": "The journey took eleven hours by bus.",
  "depart": "Our train departs at ten past six.",
  "arrive": "We arrived just before the rain started.",
  "luggage": "My luggage came on the next flight.",
  "passport": "Keep your passport in the front pocket.",
  "foreign": "He speaks three foreign languages.",
  "ferry": "The ferry crosses the bay every hour.",
  "delay": "A short delay made us miss the connection.",
  "board": "We board the plane in twenty minutes.",
  "map": "She drew a small map on a napkin.",
  "souvenir": "I bought a tiny souvenir for my sister.",
  "detour": "A detour added forty minutes to the drive.",
  "landmark": "The tower is the easiest landmark to find.",
  "itinerary": "Our itinerary leaves one free afternoon.",
  "voyage": "The voyage across the Atlantic took two weeks.",
  "harbor": "Small boats rocked gently in the harbor.",
  "remote": "They live in a remote village up the valley.",
  "scenic": "We took the scenic road along the coast.",
  "navigate": "He navigated the old town without a phone.",
  "compass": "An old compass hung above the desk.",
  "altitude": "The altitude made us breathe harder.",
  "crossing": "The crossing was rough and very slow.",
  "lodge": "We lodged in a small house near the lake.",
  "fare": "The bus fare went up again this year.",
  "hostel": "The hostel was cheap, clean and friendly.",
  "roam": "We roamed the old streets until midnight.",
  "bustling": "The station was bustling at seven.",
  "excursion": "The excursion to the island lasted a day.",
  "timezone": "My family lives one timezone away.",
  "customs": "We waited an hour at customs.",
  "outpost": "The last outpost had one shop and a well.",
  "expedition": "The expedition mapped the northern coast.",
  "layover": "We had a six hour layover in Lisbon.",
  "backpack": "They backpacked across Asia for a year.",
  "stroll": "We strolled along the river after dinner.",
  "quaint": "The village is quaint and very quiet.",
  "secluded": "They found a secluded beach past the rocks.",
  "embark": "We embark on the ferry at dawn.",
  "nomad": "He lives like a nomad, moving every month.",
  "wanderlust": "Her wanderlust started with one train ticket.",
  "circuitous": "We took a circuitous route to avoid traffic.",
  "sojourn": "Their sojourn in Rome lasted three months.",
  "panorama": "From the top you get a full panorama.",
  "itinerant": "He worked as an itinerant musician.",
  "voyager": "The old voyager had crossed every ocean.",

  /* Profissões */
  "baker": "The baker starts work at four in the morning.",
  "nurse": "A night nurse checked on him twice.",
  "farmer": "The farmer sells eggs at the Saturday market.",
  "waiter": "Our waiter remembered the whole order.",
  "cashier": "The cashier counted the change carefully.",
  "firefighter": "A firefighter carried the ladder alone.",
  "mentor": "My first mentor taught me to ask questions.",
  "plumber": "The plumber fixed the leak in an hour.",
  "carpenter": "A carpenter built these shelves by hand.",
  "tailor": "The tailor shortened my trousers today.",
  "mechanic": "Our mechanic found the problem in minutes.",
  "lawyer": "Her lawyer read every line of the contract.",
  "engineer": "The engineer explained the design simply.",
  "architect": "The architect showed us three drawings.",
  "accountant": "Our accountant files the taxes in March.",
  "journalist": "A journalist called about the story.",
  "librarian": "The librarian found the book in seconds.",
  "electrician": "An electrician rewired the whole kitchen.",
  "janitor": "The janitor opens the school at six.",
  "surgeon": "The surgeon spoke to us after the operation.",
  "therapist": "She sees a therapist every other week.",
  "paramedic": "A paramedic arrived within four minutes.",
  "welder": "The welder wore a heavy dark mask.",
  "shepherd": "The shepherd walked ahead of the flock.",
  "apprentice": "He worked two years as an apprentice.",
  "freelancer": "As a freelancer she chooses her hours.",
  "internship": "Her internship turned into a real job.",
  "artisan": "Each bowl is made by a local artisan.",
  "vocation": "Teaching is a vocation, not just a job.",
  "livelihood": "Fishing is the livelihood of this village.",

  /* Trabalho & negócios */
  "achieve": "We achieved more than we expected.",
  "deadline": "The deadline moved to next Friday.",
  "colleague": "A colleague helped me finish the report.",
  "manage": "She manages a team of eight people.",
  "client": "The client asked for one small change.",
  "meeting": "The meeting lasted twenty quiet minutes.",
  "hire": "They hired two designers last month.",
  "skilled": "He is skilled at explaining hard ideas.",
  "efficient": "The new process is far more efficient.",
  "assign": "The manager assigned the task to me.",
  "propose": "I propose we start with the simplest part.",
  "draft": "Send me a rough draft by Thursday.",
  "feedback": "Her feedback improved the whole document.",
  "promote": "They promoted him after two years.",
  "resign": "He resigned quietly at the end of June.",
  "productive": "Mornings are my most productive hours.",
  "supervise": "She supervises the night shift.",
  "strategy": "Our strategy is simple and slow.",
  "overtime": "Nobody wants overtime on a Friday.",
  "commute": "I commute by bike in the summer.",
  "shift": "My shift ends at four in the afternoon.",
  "negotiate": "They negotiated a better delivery date.",
  "persuade": "He persuaded the team to try it once.",
  "delegate": "A good manager knows how to delegate.",
  "thorough": "Her review was thorough and fair.",
  "collaborate": "Two teams collaborated on the launch.",
  "prioritize": "Prioritize the tasks that block others.",
  "deputy": "The deputy signed while she was away.",
  "milestone": "The first milestone is due in April.",
  "workload": "His workload doubled after the merger.",
  "outsource": "They outsource support to another company.",
  "stakeholder": "Every stakeholder saw the plan first.",
  "burnout": "Long weeks without rest lead to burnout.",
  "streamline": "We streamlined the approval process.",
  "leverage": "They leveraged the old code for the new app.",
  "scope": "The scope of the project keeps growing.",
  "contingency": "We kept a contingency for delays.",
  "proficiency": "His proficiency in Spanish opened doors.",
  "accountable": "Each team is accountable for its own budget.",
  "pragmatic": "She took a pragmatic view of the deadline.",

  /* Tecnologia */
  "screen": "The screen is too bright at night.",
  "device": "This device charges in half an hour.",
  "download": "Download the file before you leave home.",
  "upload": "She uploaded the photos from the trip.",
  "password": "Change your password every few months.",
  "battery": "The battery lasts a whole working day.",
  "connect": "Connect the printer to the same network.",
  "update": "The update fixed the crash on startup.",
  "browse": "I browse the news while the coffee brews.",
  "storage": "My phone is out of storage again.",
  "backup": "Keep a backup of everything important.",
  "settings": "The option is hidden deep in the settings.",
  "wireless": "The wireless keyboard needs two batteries.",
  "buffer": "The video buffers on this slow connection.",
  "software": "The software runs on any old laptop.",
  "network": "The office network went down for an hour.",
  "glitch": "A small glitch froze the whole screen.",
  "shortcut": "This shortcut saves me ten clicks a day.",
  "encrypt": "The app encrypts every message you send.",
  "bandwidth": "Video calls eat most of our bandwidth.",
  "latency": "Low latency matters more than raw speed.",
  "interface": "The interface is clean and easy to learn.",
  "algorithm": "A simple algorithm sorts the whole list.",
  "debug": "It took two hours to debug the login.",
  "deploy": "We deploy the new version on Tuesday.",
  "firmware": "The firmware update improved the battery.",
  "render": "The laptop renders the video in minutes.",
  "prototype": "The first prototype was made of cardboard.",
  "obsolete": "That format became obsolete years ago.",
  "seamless": "The transfer between devices is seamless.",
  "scalable": "The design is simple and scalable.",
  "redundancy": "Redundancy keeps the service alive during failures.",
  "throughput": "The new server doubled our throughput.",
  "deprecate": "They deprecated the old interface last year.",
  "interoperable": "The two systems are fully interoperable.",
  "overhead": "The extra checks add a little overhead.",

  /* Ciência */
  "planet": "Mars is the fourth planet from the sun.",
  "liquid": "Water is a liquid at room temperature.",
  "measure": "Measure the length twice before cutting.",
  "gravity": "Gravity pulls everything toward the ground.",
  "atom": "A single atom is far too small to see.",
  "orbit": "The station completes an orbit every ninety minutes.",
  "telescope": "Through the telescope we saw four moons.",
  "microscope": "Under the microscope the leaf looked alive.",
  "experiment": "The experiment failed twice before it worked.",
  "laboratory": "The laboratory stays open until midnight.",
  "mixture": "Stir the mixture until it turns clear.",
  "magnet": "A small magnet holds the door shut.",
  "dissolve": "Sugar dissolves faster in hot water.",
  "observe": "We observed the birds for three weeks.",
  "molecule": "A water molecule has three atoms.",
  "vapor": "Warm vapor rose from the cup.",
  "friction": "Friction slows the box on rough ground.",
  "circuit": "One loose wire broke the whole circuit.",
  "specimen": "Each specimen was labeled and stored.",
  "evaporate": "The puddles evaporated by noon.",
  "variable": "Temperature was the only variable they changed.",
  "radiation": "Thick glass blocks most of the radiation.",
  "genome": "The genome of this plant was mapped in 2018.",
  "catalyst": "The catalyst makes the reaction much faster.",
  "entropy": "Entropy explains why the room never tidies itself.",
  "calibrate": "Calibrate the scale before the first reading.",
  "empirical": "Their claim rests on empirical data.",

  /* Arte & música */
  "paint": "She paints small landscapes on Sundays.",
  "drum": "The drum kept the whole band together.",
  "guitar": "He plays guitar on the balcony at night.",
  "tune": "That tune stayed in my head all day.",
  "poem": "She read a short poem before dinner.",
  "author": "The author signed books after the reading.",
  "stage": "The lights came up on an empty stage.",
  "melody": "The melody is simple and easy to sing.",
  "rhythm": "The rhythm made everyone start moving.",
  "chorus": "Everybody sang the chorus together.",
  "lyrics": "The lyrics tell the story of a journey.",
  "sketch": "He made a quick sketch of the harbor.",
  "sculpture": "A stone sculpture stands in the square.",
  "portrait": "Her portrait hangs above the fireplace.",
  "gallery": "The gallery opens a new show tonight.",
  "novel": "I finished the novel in three evenings.",
  "audience": "The audience clapped for a full minute.",
  "choir": "The choir practices on Wednesday nights.",
  "canvas": "He stretched a fresh canvas for the painting.",
  "exhibit": "The museum exhibits her work until May.",
  "rehearse": "The band rehearsed the song eleven times.",
  "applause": "The applause lasted longer than the song.",
  "masterpiece": "That quiet little album is a masterpiece.",
  "improvise": "Good jazz players improvise every night.",
  "aesthetic": "The film has a cold, careful aesthetic.",
  "evocative": "The photograph is strangely evocative.",
  "virtuoso": "She is a virtuoso on the violin.",
  "haunting": "The final song was slow and haunting.",
  "ornate": "The theater has an ornate golden ceiling.",

  /* Ideias & raciocínio */
  "learn": "You learn faster when you practice daily.",
  "explain": "Can you explain that in simpler words?",
  "reason": "There is a good reason for the delay.",
  "example": "Give me one example from your own work.",
  "notice": "I did not notice the change at first.",
  "compare": "Compare the two answers side by side.",
  "decide": "We decided to wait another week.",
  "review": "Review your notes before the exam.",
  "concept": "The concept is simple once you draw it.",
  "theory": "His theory explains most of the results.",
  "evidence": "There is little evidence for that claim.",
  "assume": "Do not assume the file was saved.",
  "conclude": "We concluded that the plan was too costly.",
  "outline": "Write an outline before the first page.",
  "summary": "The summary fits on a single page.",
  "insight": "One small insight solved the whole problem.",
  "research": "Her research took four years to finish.",
  "method": "This method works for small groups.",
  "debate": "They debated the rule for an hour.",
  "clarify": "Let me clarify the second point.",
  "analyze": "We analyzed the data line by line.",
  "interpret": "Two experts interpreted the results differently.",
  "hypothesis": "The hypothesis was simple and testable.",
  "consistent": "His answers were consistent all week.",
  "objective": "Try to stay objective about your own work.",
  "relevant": "Only the last chapter is relevant here.",
  "assess": "The teacher assessed each project fairly.",
  "distinguish": "It is hard to distinguish the two versions.",
  "emphasize": "She emphasized the need for rest.",
  "ambiguous": "The final sentence is ambiguous.",
  "comprehend": "It took a while to comprehend the whole idea.",
  "retain": "We retain far more when we sleep well.",
  "ubiquitous": "Screens are ubiquitous in modern life.",
  "threshold": "He paused at the threshold before entering.",
  "coherent": "Her argument was calm and coherent.",
  "nuance": "The translation lost a small nuance.",
  "scrutinize": "They scrutinized every line of the contract.",
  "inference": "That inference goes beyond the evidence.",
  "paradigm": "The discovery changed the whole paradigm.",
  "substantiate": "You need data to substantiate that claim.",
  "compelling": "She made a compelling case for the change.",
  "arbitrary": "The deadline felt completely arbitrary.",
  "synthesis": "The final chapter is a synthesis of both ideas.",
  "prevalent": "That belief is still prevalent here.",
  };

  if (typeof module === "object" && module.exports) module.exports = { WORD_EXAMPLES: WORD_EXAMPLES };
  if (root) root.WORD_EXAMPLES = WORD_EXAMPLES;
})(typeof window !== "undefined" ? window : null);
