/* Type & Chill — banco de palavras.
 *
 * Formato de cada entrada:
 *   [ palavra, classe, definição em inglês, tradução em português, nível CEFR ]
 *
 * Classes:  n (substantivo) · v (verbo) · adj (adjetivo) · adv (advérbio)
 * Níveis:   A2 (básico) · B1 (intermediário) · B2 (avançado) · C1 (fluente)
 *
 * Quer adicionar palavras? Basta incluir novas linhas em qualquer tema,
 * ou criar um tema novo seguindo o mesmo formato. O jogo lê tudo daqui.
 */
(function (root) {
  "use strict";

var WORD_LEVELS = ["A2", "B1", "B2", "C1"];

var WORD_THEMES = {

  everyday: {
    label: "Dia a dia",
    words: [
      ["tidy","adj","neat and arranged in good order","arrumado, organizado","A2"],
      ["borrow","v","to take and use something, then return it","pegar emprestado","A2"],
      ["spare","adj","kept in reserve for use when needed","reserva, extra","A2"],
      ["handy","adj","useful and easy to reach or use","útil, à mão","A2"],
      ["routine","n","a fixed, regular way of doing things","rotina","A2"],
      ["grocery","n","food and small goods bought at a store","mercearia, compras","A2"],
      ["neighbor","n","a person who lives next to or near you","vizinho","A2"],
      ["schedule","n","a plan of times for doing things","agenda, cronograma","A2"],
      ["chore","n","a small, routine household task","tarefa doméstica","A2"],
      ["gentle","adj","mild, soft, and not rough","suave, gentil","A2"],
      ["crowded","adj","full of too many people or things","lotado","A2"],
      ["polite","adj","having or showing good manners","educado","A2"],
      ["messy","adj","dirty or not in order","bagunçado","A2"],
      ["afford","v","to have enough money for something","ter condições de pagar","A2"],
      ["gather","v","to bring or come together in one place","reunir, juntar","A2"],
      ["improve","v","to make or become better","melhorar","A2"],
      ["plenty","n","a full or large enough amount","bastante, fartura","A2"],
      ["shelf","n","a flat board fixed to a wall to hold things","prateleira","A2"],
      ["drawer","n","a sliding box built into furniture","gaveta","A2"],
      ["broom","n","a brush with a long handle for sweeping","vassoura","A2"],
      ["gadget","n","a small, clever, and useful device","engenhoca, aparelhinho","B1"],
      ["errand","n","a short trip to do a small task","recado, tarefa rápida","B1"],
      ["reliable","adj","able to be trusted to work well","confiável","B1"],
      ["genuine","adj","real and exactly what it appears to be","genuíno, autêntico","B1"],
      ["sturdy","adj","strong and not easily broken","robusto, firme","B1"],
      ["mend","v","to repair something torn or broken","consertar, remendar","B1"],
      ["kettle","n","a container used for boiling water","chaleira","B1"],
      ["leftover","n","food that remains after a meal","sobra de comida","B1"],
      ["frequent","adj","happening often","frequente","B1"],
      ["spacious","adj","having plenty of room inside","espaçoso","B1"],
      ["cozy","adj","warm, comfortable, and snug","aconchegante","B1"],
      ["convenient","adj","easy and well suited to your needs","conveniente, prático","B1"],
      ["awkward","adj","clumsy or causing embarrassment","constrangedor, sem jeito","B1"],
      ["stubborn","adj","refusing to change your mind","teimoso","B1"],
      ["generous","adj","willing to give and share freely","generoso","B1"],
      ["grateful","adj","feeling or showing thanks","grato","B1"],
      ["swift","adj","moving or happening quickly","rápido, veloz","B1"],
      ["patient","adj","able to wait calmly without complaint","paciente","B1"],
      ["whisper","v","to speak very softly and quietly","sussurrar","B1"],
      ["fragile","adj","delicate and easily broken","frágil","B1"],
      ["fetch","v","to go and bring something back","ir buscar","B1"],
      ["faucet","n","a device that controls the flow of water","torneira","B1"],
      ["abundant","adj","existing in very large amounts","abundante","B2"],
      ["occasional","adj","happening now and then, not often","ocasional, esporádico","B2"],
      ["punctual","adj","arriving or doing things exactly on time","pontual","B2"],
      ["spotless","adj","perfectly clean, without a single mark","impecável, imaculado","B2"],
      ["clutter","n","a messy collection of things lying around","bagunça, tralha","B2"],
      ["household","n","all the people living together in one home","lar, casa","B2"],
      ["laundry","n","clothes that need washing, or the washing itself","roupa suja, lavanderia","B2"],
      ["thrifty","adj","careful and clever with money","econômico, poupador","B2"],
      ["chatter","v","to talk quickly about unimportant things","tagarelar","B2"],
      ["linger","v","to stay somewhere longer than needed","demorar-se, permanecer","B2"],
      ["nudge","v","to push someone gently with the elbow","cutucar","B2"],
      ["hassle","n","an annoying difficulty or bother","incômodo, trabalheira","B2"],
      ["tuck","v","to push something neatly into a small space","enfiar, aconchegar","B2"],
      ["knack","n","a natural skill for doing something well","jeito, dom","C1"],
      ["mundane","adj","ordinary, dull, and lacking interest","banal, corriqueiro","C1"],
      ["makeshift","adj","made quickly from whatever is available","improvisado","C1"],
      ["meticulous","adj","showing great care about small details","meticuloso","C1"],
      ["ubiquitous","adj","seeming to be everywhere at once","onipresente","C1"]
    ]
  },

  nature: {
    label: "Natureza",
    words: [
      ["breeze","n","a light, gentle wind","brisa","A2"],
      ["dawn","n","the first light of the morning","amanhecer","A2"],
      ["dusk","n","the time of day when daylight fades","anoitecer, crepúsculo","A2"],
      ["shore","n","the land along the edge of water","margem, costa","A2"],
      ["stream","n","a small, narrow flowing body of water","riacho","A2"],
      ["pebble","n","a small, smooth, rounded stone","seixo, pedrinha","A2"],
      ["thunder","n","the loud sound that follows lightning","trovão","A2"],
      ["valley","n","low land lying between hills or mountains","vale","A2"],
      ["shallow","adj","not deep, measured from top to bottom","raso","A2"],
      ["cave","n","a large natural hole in a hill or cliff","caverna","A2"],
      ["dew","n","tiny drops of water that form overnight","orvalho","B1"],
      ["frost","n","a thin white layer of ice crystals","geada","B1"],
      ["summit","n","the highest point of a mountain","cume, cimo","B1"],
      ["horizon","n","the line where the sky meets the earth","horizonte","B1"],
      ["blossom","v","to produce flowers; to come into bloom","florescer","B1"],
      ["meadow","n","a field of grass and wildflowers","prado, campina","B1"],
      ["misty","adj","covered with a thin layer of fog","enevoado","B1"],
      ["ripple","n","a small wave on the surface of water","ondulação, marolinha","B1"],
      ["fern","n","a green plant with soft, feathery leaves","samambaia","B1"],
      ["moss","n","a soft green plant on damp ground or stone","musgo","B1"],
      ["tide","n","the regular rise and fall of the sea","maré","B1"],
      ["drizzle","n","light, fine rain","garoa, chuvisco","B1"],
      ["vast","adj","extremely large in size or area","vasto, imenso","B1"],
      ["migrate","v","to move to another region with the seasons","migrar","B1"],
      ["wander","v","to move around with no fixed path","vagar, perambular","B1"],
      ["drift","v","to float slowly, carried by wind or water","flutuar à deriva","B1"],
      ["steep","adj","rising or falling at a sharp angle","íngreme","B1"],
      ["cliff","n","a high, steep face of rock","penhasco, falésia","B1"],
      ["flock","n","a group of birds or sheep together","bando, rebanho","B1"],
      ["sprout","v","to begin to grow and appear","brotar","B1"],
      ["lush","adj","green, thick, and full of growth","exuberante, viçoso","B2"],
      ["canopy","n","the leafy upper layer of a forest","copa da floresta, dossel","B2"],
      ["glacier","n","a huge, slow-moving mass of ice","geleira","B2"],
      ["grove","n","a small group of trees","bosque, arvoredo","B2"],
      ["serene","adj","calm, peaceful, and untroubled","sereno","B2"],
      ["barren","adj","bare land where little can grow","árido, estéril","B2"],
      ["fertile","adj","able to produce many plants or crops","fértil","B2"],
      ["hibernate","v","to sleep through the winter months","hibernar","B2"],
      ["graze","v","to eat grass growing in a field","pastar","B2"],
      ["radiant","adj","shining brightly; glowing with warmth","radiante","B2"],
      ["blaze","v","to burn or shine with bright flame","arder, resplandecer","B2"],
      ["twilight","n","the soft light after sunset","lusco-fusco, penumbra","B2"],
      ["hollow","n","a small dip or empty space in the ground","depressão, cavidade","B2"],
      ["marsh","n","soft, wet land covered with grass","pântano, brejo","B2"],
      ["swarm","n","a large moving group of insects","enxame","B2"],
      ["prey","n","an animal hunted by another for food","presa","B2"],
      ["burrow","n","a hole in the ground made by an animal","toca","B2"],
      ["thrive","v","to grow strongly and do very well","prosperar, vicejar","B2"],
      ["wither","v","to dry up and lose freshness","murchar","B2"],
      ["rustle","v","to make a soft sound like moving leaves","farfalhar","B2"],
      ["cascade","n","a small waterfall falling over rocks","cascata","B2"],
      ["ember","n","a small piece of glowing coal or wood","brasa","B2"],
      ["haze","n","a light mist that makes seeing hard","névoa, bruma","B2"],
      ["meander","v","to follow a slow, winding course","serpentear","C1"],
      ["glisten","v","to shine with a soft, wet light","reluzir, cintilar","C1"],
      ["gale","n","a very strong wind","vendaval","C1"],
      ["tranquil","adj","quiet, calm, and free from disturbance","tranquilo","C1"],
      ["pristine","adj","clean and untouched, as in its first state","imaculado, intocado","C1"],
      ["verdant","adj","green with fresh growing plants","verdejante","C1"],
      ["dappled","adj","marked with spots of light and shade","salpicado de luz","C1"]
    ]
  },

  travel: {
    label: "Viagem",
    words: [
      ["journey","n","the act of traveling from one place to another","jornada, viagem","A2"],
      ["depart","v","to leave, especially to begin a trip","partir","A2"],
      ["arrive","v","to reach a place or destination","chegar","A2"],
      ["luggage","n","the bags you carry when traveling","bagagem","A2"],
      ["passport","n","an official document for foreign travel","passaporte","A2"],
      ["foreign","adj","belonging to another country","estrangeiro","A2"],
      ["ferry","n","a boat that carries people across water","balsa, ferry","A2"],
      ["delay","n","a period of waiting caused by a problem","atraso","A2"],
      ["board","v","to get on a plane, ship, or train","embarcar","A2"],
      ["map","n","a drawing showing where places are","mapa","A2"],
      ["souvenir","n","an object kept to remember a place","lembrança, souvenir","B1"],
      ["detour","n","a longer route taken to avoid something","desvio","B1"],
      ["landmark","n","a well-known feature used to find your way","ponto de referência","B1"],
      ["itinerary","n","a planned route or travel schedule","itinerário","B1"],
      ["voyage","n","a long journey, often made by sea","travessia, viagem marítima","B1"],
      ["currency","n","the money used in a particular country","moeda, câmbio","B1"],
      ["harbor","n","a sheltered place where ships stay safely","porto","B1"],
      ["remote","adj","far away and hard to reach","remoto, distante","B1"],
      ["scenic","adj","having beautiful natural views","panorâmico, cênico","B1"],
      ["navigate","v","to find and follow the way to a place","navegar, se orientar","B1"],
      ["compass","n","a tool that shows direction","bússola","B1"],
      ["altitude","n","the height of something above sea level","altitude","B1"],
      ["crossing","n","a trip across water or a border","travessia","B1"],
      ["lodge","v","to stay somewhere for a short time","hospedar-se","B1"],
      ["fare","n","the money paid for a trip","passagem, tarifa","B1"],
      ["hostel","n","a cheap place to sleep while traveling","albergue","B1"],
      ["roam","v","to move about freely over a wide area","perambular, vagar","B2"],
      ["bustling","adj","full of busy, lively activity","movimentado, fervilhante","B2"],
      ["excursion","n","a short trip taken for pleasure","excursão, passeio","B2"],
      ["timezone","n","a region that shares the same clock time","fuso horário","B2"],
      ["customs","n","the place where luggage is checked at a border","alfândega","B2"],
      ["outpost","n","a small settlement far from a city","posto avançado","B2"],
      ["expedition","n","an organized journey with a purpose","expedição","B2"],
      ["layover","n","a short stop between two flights","escala","B2"],
      ["backpack","v","to travel cheaply carrying your bag","mochilar","B2"],
      ["stroll","v","to walk slowly for pleasure","passear, caminhar sem pressa","B2"],
      ["quaint","adj","charming in an old-fashioned way","pitoresco","B2"],
      ["secluded","adj","quiet, private, and away from people","isolado, reservado","B2"],
      ["embark","v","to begin a journey or a new project","embarcar, iniciar","B2"],
      ["nomad","n","a person who moves from place to place","nômade","B2"],
      ["wanderlust","n","a strong desire to travel and explore","desejo de viajar","C1"],
      ["circuitous","adj","longer and less direct than it needs to be","tortuoso, indireto","C1"],
      ["sojourn","n","a temporary stay in a place","estadia temporária","C1"],
      ["panorama","n","a wide, unbroken view of an area","panorama","C1"],
      ["itinerant","adj","traveling from place to place for work","itinerante","C1"],
      ["voyager","n","a person who makes long journeys","viajante","C1"]
    ]
  },

  work: {
    label: "Trabalho",
    words: [
      ["achieve","v","to reach a goal through effort","alcançar, conquistar","A2"],
      ["deadline","n","the latest time by which to finish","prazo final","A2"],
      ["colleague","n","a person you work with","colega de trabalho","A2"],
      ["manage","v","to be in charge of; to handle","gerenciar, administrar","A2"],
      ["client","n","a person who pays for a service","cliente","A2"],
      ["meeting","n","a planned gathering to discuss work","reunião","A2"],
      ["salary","n","the money paid regularly for a job","salário","A2"],
      ["hire","v","to give someone a job","contratar","A2"],
      ["skilled","adj","having ability gained from training","qualificado, habilidoso","B1"],
      ["diligent","adj","hardworking and careful","diligente, aplicado","B1"],
      ["efficient","adj","working well without wasting effort","eficiente","B1"],
      ["assign","v","to give someone a particular task","atribuir, designar","B1"],
      ["propose","v","to suggest a plan or idea","propor","B1"],
      ["draft","n","an early, unfinished version of a document","rascunho","B1"],
      ["feedback","n","advice about how to improve something","retorno, feedback","B1"],
      ["mentor","n","an experienced person who guides you","mentor","B1"],
      ["promote","v","to move someone to a higher position","promover","B1"],
      ["resign","v","to leave a job by your own choice","pedir demissão","B1"],
      ["ambitious","adj","having a strong wish to succeed","ambicioso","B1"],
      ["productive","adj","getting a great deal done","produtivo","B1"],
      ["supervise","v","to watch over and direct work","supervisionar","B1"],
      ["invoice","n","a bill listing goods or services","fatura, nota","B1"],
      ["strategy","n","a careful plan to reach a goal","estratégia","B1"],
      ["overtime","n","extra hours worked beyond the normal time","hora extra","B1"],
      ["commute","v","to travel regularly to and from work","deslocar-se para o trabalho","B1"],
      ["shift","n","a set period of working hours","turno","B1"],
      ["negotiate","v","to reach an agreement by discussion","negociar","B2"],
      ["persuade","v","to make someone agree by giving reasons","persuadir, convencer","B2"],
      ["delegate","v","to give tasks to other people","delegar","B2"],
      ["thorough","adj","complete and careful in every detail","minucioso, completo","B2"],
      ["collaborate","v","to work together toward a goal","colaborar","B2"],
      ["revenue","n","the money a business earns","receita, faturamento","B2"],
      ["prioritize","v","to deal with the most important things first","priorizar","B2"],
      ["deputy","n","a person who acts in place of another","substituto, vice","B2"],
      ["milestone","n","an important stage in a project","marco, etapa importante","B2"],
      ["workload","n","the amount of work a person must do","carga de trabalho","B2"],
      ["outsource","v","to pay another company to do part of the work","terceirizar","B2"],
      ["stakeholder","n","a person affected by what a project does","parte interessada","B2"],
      ["burnout","n","exhaustion caused by too much work","esgotamento, burnout","B2"],
      ["streamline","v","to make a process simpler and faster","simplificar, otimizar","C1"],
      ["leverage","v","to use something you have for greater effect","alavancar","C1"],
      ["scope","n","the range of what a project covers","escopo, abrangência","C1"],
      ["contingency","n","a plan made for something that might happen","contingência, plano B","C1"],
      ["proficiency","n","a high level of skill in something","proficiência","C1"],
      ["accountable","adj","required to explain your decisions","responsável, prestando contas","C1"],
      ["pragmatic","adj","dealing with things in a practical way","pragmático","C1"]
    ]
  },

  feelings: {
    label: "Emoções & mente",
    words: [
      ["eager","adj","wanting to do something very much","ansioso por, entusiasmado","A2"],
      ["proud","adj","pleased about an achievement","orgulhoso","A2"],
      ["cheerful","adj","visibly happy and full of good spirits","alegre, animado","A2"],
      ["bold","adj","brave and confident","corajoso, ousado","A2"],
      ["mood","n","a temporary state of mind or feeling","humor, estado de espírito","A2"],
      ["curious","adj","eager to learn or know something","curioso","A2"],
      ["imagine","v","to form a picture of something in the mind","imaginar","A2"],
      ["confident","adj","feeling sure of yourself","confiante","A2"],
      ["anxious","adj","worried and uneasy about something","ansioso, preocupado","B1"],
      ["weary","adj","very tired, often after long effort","exausto, cansado","B1"],
      ["content","adj","quietly happy and satisfied","contente, satisfeito","B1"],
      ["hesitate","v","to pause because you feel unsure","hesitar","B1"],
      ["sincere","adj","honest and without pretending","sincero","B1"],
      ["humble","adj","modest; not proud or boastful","humilde","B1"],
      ["gloomy","adj","sad and without hope","sombrio, melancólico","B1"],
      ["tender","adj","gentle, kind, and loving","terno, carinhoso","B1"],
      ["timid","adj","shy and easily frightened","tímido, receoso","B1"],
      ["recall","v","to bring a memory back to mind","recordar, lembrar","B1"],
      ["comfort","v","to ease the worry or sorrow of someone","confortar","B1"],
      ["admire","v","to respect and like something greatly","admirar","B1"],
      ["forgive","v","to stop feeling anger toward someone","perdoar","B1"],
      ["relieve","v","to reduce pain, worry, or pressure","aliviar","B1"],
      ["restless","adj","unable to rest or stay still","inquieto, agitado","B1"],
      ["fond","adj","having warm, affectionate feelings","afeiçoado","B1"],
      ["cherish","v","to hold something dear and care for it","prezar, estimar","B2"],
      ["ponder","v","to think about something carefully","ponderar, refletir","B2"],
      ["astonish","v","to surprise someone greatly","espantar, assombrar","B2"],
      ["soothe","v","to make calm or less painful","acalmar, suavizar","B2"],
      ["yearn","v","to want something very deeply","ansiar, anelar","B2"],
      ["dread","v","to feel great fear about what is coming","temer, ter pavor","B2"],
      ["resent","v","to feel bitter or angry about something","ressentir-se","B2"],
      ["empathy","n","the ability to share the feelings of others","empatia","B2"],
      ["vivid","adj","producing strong, clear mental images","vívido, nítido","B2"],
      ["overwhelm","v","to affect someone with very strong feeling","sobrecarregar, dominar","B2"],
      ["grief","n","deep sorrow, especially after a loss","luto, pesar","B2"],
      ["nostalgia","n","a fond, slightly sad memory of the past","nostalgia","B2"],
      ["compassion","n","kind concern for the suffering of others","compaixão","B2"],
      ["reassure","v","to remove the doubts or fears of someone","tranquilizar","B2"],
      ["apprehensive","adj","nervous about something that may happen","apreensivo","B2"],
      ["exhilarating","adj","making you feel very happy and alive","emocionante, revigorante","B2"],
      ["wistful","adj","gently sad and full of longing","saudoso, melancólico","C1"],
      ["serenity","n","a calm and untroubled state of mind","serenidade","C1"],
      ["poignant","adj","touching and deeply moving","comovente, tocante","C1"],
      ["elated","adj","extremely happy and excited","exultante, eufórico","C1"],
      ["indifferent","adj","having no interest or feeling either way","indiferente","C1"],
      ["introspective","adj","looking closely at your own thoughts","introspectivo","C1"],
      ["solace","n","comfort found in a time of sadness","consolo","C1"],
      ["ambivalent","adj","having two opposite feelings at once","ambivalente","C1"]
    ]
  },

  food: {
    label: "Comida & bebida",
    words: [
      ["bake","v","to cook food in an oven","assar","A2"],
      ["boil","v","to heat a liquid until it bubbles","ferver","A2"],
      ["slice","n","a thin flat piece cut from something","fatia","A2"],
      ["tasty","adj","having a pleasant flavor","saboroso","A2"],
      ["sour","adj","having a sharp taste like lemon","azedo","A2"],
      ["ripe","adj","fully grown and ready to eat","maduro","A2"],
      ["snack","n","a small amount of food between meals","lanche","A2"],
      ["recipe","n","a set of instructions for cooking a dish","receita","A2"],
      ["chop","v","to cut into small pieces","picar, cortar","A2"],
      ["stir","v","to move a liquid around with a spoon","mexer, misturar","A2"],
      ["roast","v","to cook with dry heat in an oven or fire","assar, tostar","B1"],
      ["simmer","v","to cook gently just below boiling","cozinhar em fogo baixo","B1"],
      ["season","v","to add salt, herbs, or spices to food","temperar","B1"],
      ["crisp","adj","pleasantly hard and easy to break","crocante","B1"],
      ["chewy","adj","needing a lot of chewing before swallowing","borrachudo, que exige mastigar","B1"],
      ["bland","adj","having very little flavor","sem graça, insosso","B1"],
      ["nourish","v","to give the food needed to grow and stay well","nutrir","B1"],
      ["portion","n","the amount of food served to one person","porção","B1"],
      ["leftovers","n","food remaining from an earlier meal","sobras","B1"],
      ["brew","v","to make tea, coffee, or beer","preparar, fazer infusão","B1"],
      ["sip","v","to drink slowly in small amounts","tomar aos goles","B1"],
      ["ingredient","n","one of the foods used to make a dish","ingrediente","B1"],
      ["savory","adj","salty or spicy rather than sweet","salgado, saboroso","B2"],
      ["hearty","adj","large and satisfying, said of a meal","farto, reforçado","B2"],
      ["fragrant","adj","having a pleasant, noticeable smell","perfumado, aromático","B2"],
      ["zest","n","the outer skin of a lemon or orange used in cooking","raspas de casca","B2"],
      ["marinate","v","to soak food in a flavored liquid","marinar","B2"],
      ["garnish","v","to decorate a dish with something small","guarnecer, decorar","B2"],
      ["knead","v","to press and fold dough with your hands","sovar a massa","B2"],
      ["whisk","v","to beat eggs or cream quickly","bater, mexer rápido","B2"],
      ["sizzle","v","to make a hissing sound while frying","chiar, fritar","B2"],
      ["craving","n","a strong desire for a particular food","desejo, vontade","B2"],
      ["nutritious","adj","full of the substances the body needs","nutritivo","B2"],
      ["stale","adj","no longer fresh, especially bread","velho, dormido","B2"],
      ["hydrate","v","to give the body enough water","hidratar","B2"],
      ["sumptuous","adj","impressive, expensive, and generous","suntuoso, lauto","C1"],
      ["palate","n","the ability to taste and judge flavors","paladar","C1"],
      ["decadent","adj","rich and pleasurable in an excessive way","decadente, indulgente","C1"],
      ["succulent","adj","juicy and full of flavor","suculento","C1"],
      ["culinary","adj","relating to cooking and the kitchen","culinário","C1"],
      ["delectable","adj","extremely pleasing to taste","delicioso, deleitável","C1"]
    ]
  },

  city: {
    label: "Cidade & casa",
    words: [
      ["street","n","a public road in a town or city","rua","A2"],
      ["bridge","n","a structure built to cross over something","ponte","A2"],
      ["market","n","a place where goods are bought and sold","mercado, feira","A2"],
      ["library","n","a building where books are kept to borrow","biblioteca","A2"],
      ["rooftop","n","the flat top surface of a building","laje, cobertura","A2"],
      ["corner","n","the point where two streets meet","esquina","A2"],
      ["noisy","adj","full of loud sound","barulhento","A2"],
      ["rent","v","to pay to use a home or object","alugar","A2"],
      ["balcony","n","a small platform outside an upper window","varanda, sacada","B1"],
      ["alley","n","a narrow street between buildings","beco","B1"],
      ["sidewalk","n","the paved path beside a street","calçada","B1"],
      ["district","n","an area of a city with its own character","bairro, distrito","B1"],
      ["landlord","n","a person who rents a home to others","senhorio, locador","B1"],
      ["tenant","n","a person who pays to live in a place","inquilino","B1"],
      ["ceiling","n","the upper inside surface of a room","teto","B1"],
      ["hallway","n","a passage connecting rooms","corredor","B1"],
      ["fence","n","a barrier around a yard or field","cerca","B1"],
      ["basement","n","a room below ground level in a building","porão, subsolo","B1"],
      ["cottage","n","a small, simple house in the country","chalé, casinha","B1"],
      ["skyline","n","the outline of buildings against the sky","horizonte urbano","B1"],
      ["suburb","n","an area of homes outside the city center","subúrbio","B1"],
      ["traffic","n","the vehicles moving along a road","trânsito","B1"],
      ["commuter","n","a person who travels daily to work","quem se desloca ao trabalho","B2"],
      ["pedestrian","n","a person walking rather than driving","pedestre","B2"],
      ["dwelling","n","a place where a person lives","moradia","B2"],
      ["courtyard","n","an open space enclosed by walls","pátio interno","B2"],
      ["renovate","v","to repair and improve an old building","reformar","B2"],
      ["cluttered","adj","filled with too many things","abarrotado, atulhado","B2"],
      ["cramped","adj","too small and without enough room","apertado","B2"],
      ["vacant","adj","empty and available to use","vago, desocupado","B2"],
      ["outskirts","n","the outer parts of a town","arredores, periferia","B2"],
      ["plaza","n","an open public square in a city","praça","B2"],
      ["thoroughfare","n","a main road through a place","via principal","C1"],
      ["dilapidated","adj","old and falling apart from neglect","dilapidado, em ruínas","C1"],
      ["labyrinthine","adj","full of confusing, winding paths","labiríntico","C1"],
      ["sprawling","adj","spreading out over a large area","que se espalha, extenso","C1"],
      ["hub","n","a busy center of activity","polo, centro","C1"],
      ["threshold","n","the strip of floor at a doorway","soleira, limiar","C1"]
    ]
  },

  body: {
    label: "Corpo & saúde",
    words: [
      ["breathe","v","to take air into the body and let it out","respirar","A2"],
      ["stretch","v","to extend the body to make it looser","alongar, esticar","A2"],
      ["rest","v","to stop activity to recover strength","descansar","A2"],
      ["ache","n","a steady, dull pain","dor contínua","A2"],
      ["healthy","adj","in good physical condition","saudável","A2"],
      ["wound","n","an injury that breaks the skin","ferida","A2"],
      ["dizzy","adj","feeling that things are spinning","tonto","A2"],
      ["sneeze","v","to blow air out of the nose suddenly","espirrar","A2"],
      ["heal","v","to become healthy again","curar, sarar","B1"],
      ["swollen","adj","larger than normal because of injury","inchado","B1"],
      ["sore","adj","painful when touched or moved","dolorido","B1"],
      ["recover","v","to return to normal health","recuperar-se","B1"],
      ["posture","n","the way you hold your body","postura","B1"],
      ["exhausted","adj","extremely tired","exausto","B1"],
      ["nutrition","n","the process of getting the right food","nutrição","B1"],
      ["symptom","n","a sign that shows an illness","sintoma","B1"],
      ["remedy","n","something that cures or improves a problem","remédio, solução","B1"],
      ["strain","n","an injury caused by too much effort","distensão, esforço","B1"],
      ["pulse","n","the regular beat of blood in the body","pulso, pulsação","B1"],
      ["fatigue","n","extreme tiredness after effort","fadiga","B2"],
      ["soothing","adj","making pain or worry go away","calmante, reconfortante","B2"],
      ["nourishing","adj","giving the body what it needs to be well","nutritivo","B2"],
      ["endurance","n","the ability to keep going for a long time","resistência","B2"],
      ["flexible","adj","able to bend without breaking","flexível","B2"],
      ["immune","adj","protected against a disease","imune","B2"],
      ["insomnia","n","the inability to sleep","insônia","B2"],
      ["mindful","adj","paying calm attention to the present","atento, consciente","B2"],
      ["restorative","adj","having the power to bring back strength","restaurador","B2"],
      ["chronic","adj","lasting a long time and hard to cure","crônico","B2"],
      ["relapse","n","a return of an illness after improvement","recaída","B2"],
      ["invigorating","adj","making you feel fresh and full of energy","revigorante","C1"],
      ["resilience","n","the ability to recover quickly from difficulty","resiliência","C1"],
      ["sedentary","adj","spending much time sitting and not moving","sedentário","C1"],
      ["ailment","n","a minor illness or health problem","achaque, mal-estar","C1"],
      ["convalesce","v","to rest and get better after an illness","convalescer","C1"],
      ["vitality","n","strong physical and mental energy","vitalidade","C1"]
    ]
  },

  tech: {
    label: "Tecnologia",
    words: [
      ["screen","n","the flat surface that shows images","tela","A2"],
      ["device","n","a machine made for a particular job","dispositivo, aparelho","A2"],
      ["download","v","to copy data from the internet to a device","baixar","A2"],
      ["upload","v","to send data from a device to the internet","enviar, subir","A2"],
      ["password","n","a secret word used to get access","senha","A2"],
      ["battery","n","the part that stores power in a device","bateria","A2"],
      ["connect","v","to join two things so they work together","conectar","A2"],
      ["update","v","to change something to the newest version","atualizar","A2"],
      ["browse","v","to look through pages without a fixed goal","navegar, folhear","B1"],
      ["storage","n","the space where data is kept","armazenamento","B1"],
      ["backup","n","a spare copy kept in case of loss","cópia de segurança","B1"],
      ["settings","n","the options that control how a device works","configurações","B1"],
      ["wireless","adj","working without cables","sem fio","B1"],
      ["buffer","v","to store data in advance so it plays smoothly","carregar, armazenar temporariamente","B1"],
      ["software","n","the programs that run on a computer","software, programas","B1"],
      ["network","n","a group of connected computers","rede","B1"],
      ["glitch","n","a small, sudden fault in a system","falha, bug","B1"],
      ["shortcut","n","a faster way to do something","atalho","B1"],
      ["encrypt","v","to convert data into a secret code","criptografar","B2"],
      ["bandwidth","n","how much data a connection can carry","largura de banda","B2"],
      ["latency","n","the delay before data starts moving","latência, atraso","B2"],
      ["interface","n","the part of a system a person interacts with","interface","B2"],
      ["algorithm","n","a set of steps a computer follows","algoritmo","B2"],
      ["debug","v","to find and remove faults in a program","depurar, corrigir erros","B2"],
      ["deploy","v","to put software into real use","implantar, publicar","B2"],
      ["firmware","n","software built into a piece of hardware","firmware","B2"],
      ["render","v","to produce an image from data","renderizar","B2"],
      ["prototype","n","an early model built to test an idea","protótipo","B2"],
      ["obsolete","adj","no longer used because something better exists","obsoleto","B2"],
      ["seamless","adj","working smoothly with no visible joins","integrado, sem emendas","B2"],
      ["scalable","adj","able to grow without breaking down","escalável","C1"],
      ["redundancy","n","extra parts kept in case one fails","redundância","C1"],
      ["throughput","n","the amount of work done in a period","vazão, taxa de processamento","C1"],
      ["deprecate","v","to mark something as no longer recommended","descontinuar","C1"],
      ["interoperable","adj","able to work with other systems","interoperável","C1"],
      ["overhead","n","the extra cost or effort a process requires","custo adicional, sobrecarga","C1"]
    ]
  },

  ideas: {
    label: "Ideias & estudo",
    words: [
      ["learn","v","to gain knowledge or skill","aprender","A2"],
      ["explain","v","to make something clear to someone","explicar","A2"],
      ["reason","n","the cause or explanation for something","razão, motivo","A2"],
      ["example","n","a thing used to show what you mean","exemplo","A2"],
      ["notice","v","to become aware of something","notar, perceber","A2"],
      ["compare","v","to look at how things are alike or different","comparar","A2"],
      ["decide","v","to make a choice after thinking","decidir","A2"],
      ["review","v","to look at something again to check it","revisar","A2"],
      ["concept","n","a general idea about something","conceito","B1"],
      ["theory","n","an idea that explains how something works","teoria","B1"],
      ["evidence","n","facts that show something is true","evidência, provas","B1"],
      ["assume","v","to accept something as true without proof","supor, presumir","B1"],
      ["conclude","v","to decide something after thinking","concluir","B1"],
      ["outline","n","a short plan showing the main points","esboço, roteiro","B1"],
      ["summary","n","a short account of the main points","resumo","B1"],
      ["insight","n","a clear, useful understanding of something","percepção, insight","B1"],
      ["research","n","careful study to find new facts","pesquisa","B1"],
      ["method","n","a planned way of doing something","método","B1"],
      ["debate","v","to discuss opposing views on a topic","debater","B1"],
      ["clarify","v","to make something easier to understand","esclarecer","B1"],
      ["analyze","v","to examine something in detail","analisar","B2"],
      ["interpret","v","to explain the meaning of something","interpretar","B2"],
      ["hypothesis","n","an idea to be tested by research","hipótese","B2"],
      ["consistent","adj","staying the same and not contradicting","consistente, coerente","B2"],
      ["objective","adj","based on facts, not on feelings","objetivo, imparcial","B2"],
      ["relevant","adj","closely connected to the matter at hand","relevante, pertinente","B2"],
      ["assess","v","to judge the quality or value of something","avaliar","B2"],
      ["distinguish","v","to see the difference between things","distinguir","B2"],
      ["emphasize","v","to give special importance to something","enfatizar","B2"],
      ["ambiguous","adj","having more than one possible meaning","ambíguo","B2"],
      ["comprehend","v","to understand something fully","compreender","B2"],
      ["retain","v","to keep something in your memory","reter, guardar","B2"],
      ["coherent","adj","clear, logical, and well connected","coerente","C1"],
      ["nuance","n","a very small difference in meaning","nuance, sutileza","C1"],
      ["scrutinize","v","to examine something very closely","escrutinar, examinar a fundo","C1"],
      ["inference","n","a conclusion drawn from evidence","inferência","C1"],
      ["paradigm","n","a typical model or way of thinking","paradigma","C1"],
      ["substantiate","v","to support a claim with evidence","comprovar, fundamentar","C1"],
      ["compelling","adj","so convincing that it holds attention","convincente, cativante","C1"],
      ["arbitrary","adj","chosen by chance rather than by reason","arbitrário","C1"],
      ["synthesis","n","the combining of ideas into a whole","síntese","C1"],
      ["prevalent","adj","common and widespread in a place or time","predominante, difundido","C1"]
    ]
  }

};

  root.WORD_LEVELS = WORD_LEVELS;
  root.WORD_THEMES = WORD_THEMES;
  if (typeof module === "object" && module.exports) {
    module.exports = { WORD_LEVELS: WORD_LEVELS, WORD_THEMES: WORD_THEMES };
  }
})(typeof window !== "undefined" ? window : globalThis);
